cloud:
  aws:
    stack:
      auto: false
    credentials:
      access-key: ${ AWS_ACCESS_KEY_ID }
      secret-key: ${ AWS_SECRET_ACCESS_KEY }
    s3:
      endpoint: ${AWS_REGIONAL_ENDPOINT }

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ MYSQL_URL }
    username: ${ MYSQL_HOST }
    password: ${ MYSQL_PASSWORD }
  jpa:
    generate-ddl: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      com.amazonaws.util.EC2MetadataUtils: error


security:
  jwt:
    secret: ${ JWT_SECRET }

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
