- name: Set Yaml
  uses: microsoft/variable-substitution@v1
  with:
    files: ${{ env.RESOURCE_PATH }}
  env:
    cloud.aws.s3.bucket.url: ${{ AWS_S3_BUCKET_URL }}
    
    spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
    spring.datasource.url: ${{ MYSQL_URL }}
    spring.datasource.username: root
    spring.datasource.password: ${{ MYSQL_PASSWORD }}
    spring.jpa.generate-ddl: true
    
    server.servlet.encoding.charset: utf-8
    server.servlet.encoding.enabled: true
    server.servlet.encoding.force: true
    
    spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

    spring.jpa.hibernate.ddl-auto: update
    spring.profiles.include: aws

    cloud.aws.stack.auto: false
